# Generated by Django 4.1.1 on 2023-02-21 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.ForeignKey(default=[0], on_delete=django.db.models.deletion.SET_DEFAULT, related_name='countries', to='cities_light.country', verbose_name='Country'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
