# Generated by Django 4.1.1 on 2023-02-21 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_product_country_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16, verbose_name='First name')),
                ('last_name', models.CharField(max_length=16, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('post_code', models.CharField(max_length=18, verbose_name='City')),
                ('created', models.DateField(verbose_name='Created')),
                ('paid', models.BooleanField(default=True)),
                ('address', models.TextField(verbose_name='Address')),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name="Toy's name")),
            ],
        ),
    ]
