# Generated by Django 4.1.1 on 2023-02-21 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_city_order_country_alter_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 2, 21, 23, 35, 17, 704, tzinfo=datetime.timezone.utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.CharField(max_length=18, verbose_name='Post code'),
        ),
    ]
