# Generated by Django 4.1.1 on 2023-02-22 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_order_created_alter_order_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
    ]
